import secApi from './index.js';

export const {
  setApiKey,
  queryApi,
  fullTextSearchApi,
  downloadApi,
  renderApi,
  pdfGeneratorApi,
  xbrlApi,
  extractorApi,
  mappingApi,
  formAdvApi,
  insiderTradingApi,
  form144Api,
  form13FHoldingsApi,
  form13FCoverPagesApi,
  formNportApi,
  form13DGApi,
  formNcenApi,
  formNpxApi,
  formS1424B4Api,
  formDApi,
  formCApi,
  regASearchApi,
  form1AApi,
  form1KApi,
  form1ZApi,
  form8KApi,
  execCompApi,
  directorsBoardMembersApi,
  floatApi,
  subsidiaryApi,
  secEnforcementActionsApi,
  secLitigationsApi,
  secAdminProceedingsApi,
  aaerApi,
  sroFilingsApi,
  edgarEntitiesApi,
  auditFeesApi,
  edgarIndexApi,
  datasetsApi,
} = secApi;

export default secApi;
